apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
spec:
    selector:
      matchLabels:
       run: nginx
    replicas: 3
    template:
      metadata:
        labels:
          run: nginx
      spec:
          containers:
            - name: fintest 
              image: mohmagdy1016/fintest:37
              ports:
              - containerPort: 5000
           
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    run: nginx
  ports:
    - name: http
      protocol: TCP
      port: 5000
      
    
         
